# Generated by Django 6.0.4

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resoliq", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="movement",
            field=models.CharField(
                choices=[("IN", "Ingreso"), ("OUT", "Retiro")],
                default="IN",
                max_length=3,
            ),
        ),
    ]

