# Generated by Django 5.0.6 on 2024-07-09 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resoliq', '0002_registerresidue_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='commune',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='contact_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='executive',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
